### PR TITLE
Fix

### PR DESCRIPTION
**Pull request by FabianWilkens**
## Problem

- Unable to upgrade from 3.39.1~ynh1
#50 
#51 
- Missing "https://" in prefilld "Custom sync server" field

## Solution

- Fix install script
- Fix upgrade script 
- Update DISCLAIMER.md

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by FabianWilkens** [comment]
!testme

**Comment by Veehem** [comment]
Same problem
dpkg: warning: version 'v8.0.1' has bad syntax: version number does not start with digit
[Error] Upgrade failed.
sh: 0: getcwd() failed: No such file or directory

**Comment by FabianWilkens** [comment]
!testme

**Comment by Veehem** [comment]
Right now, still the same problem

**Pull request merged**
